layout_spectrum: 0.8949286676943302
typography_spectrum: 0.7800459896679968
color:
  brandStrength: 0.4633093506563455
  lightness: 0.5607106627430767
  saturation: 0.5387764880433679
  rhythmicContrast: 0.22393090347759426
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
github: true
author:
  name: MOTION BLUR
  email: MOTIONBLURNYC@MAC.COM
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a4b77d6c-441b-4f3a-b303-021a91bada51.png
name: MOTION BLUR
navigation:
  - name: EDITORIAL
    id: 0cb10c10-5d1a-4edb-b704-62569d4ea3a7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8dc144c2-d608-4e9e-a726-72f0579235f9.png
title: KEEP IT STUPID SIMPLE.
description: ' '
purpose:
  - type: contact
    url: 'mailto:motionblurnyc@mac.com'
    label: Contact us
